/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kevin' at '16-11-12 下午9:31' with Gradle 3.1
 *
 * @author Kevin, @date 16-11-12 下午9:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
